# Generated by Django 6.0.4 on 2026-06-09 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('launched_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'associations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssociationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_prefix', models.CharField(default='MEMBER', max_length=20)),
                ('subscription_rate', models.BigIntegerField(default=100000)),
                ('bot_threshold', models.BigIntegerField(default=500000000)),
                ('association_share', models.IntegerField(default=20)),
                ('platform_share', models.IntegerField(default=80)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1a3a5c', max_length=10)),
                ('secondary_color', models.CharField(default='#c9a84c', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='Powered by Cool Microfinance Bank · Developed by Iprolance LLC', max_length=200)),
                ('wallet_provider', models.CharField(default='Cool Microfinance Bank', max_length=100)),
                ('wallet_provider_short', models.CharField(default='Cool MFB', max_length=30)),
                ('toilet_association_share', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='associations.association')),
            ],
            options={
                'db_table': 'association_configs',
            },
        ),
    ]
