# Generated by Django 6.0.4 on 2026-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationconfig',
            name='bill_association_share',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='associationconfig',
            name='bill_platform_share',
            field=models.IntegerField(default=20),
        ),
    ]
