# Generated by Django 6.0.4 on 2026-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_associationconfig_bill_association_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationconfig',
            name='bill_association_share',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='associationconfig',
            name='bill_platform_share',
            field=models.IntegerField(default=0),
        ),
    ]
