# Generated by Django 6.0.4 on 2026-05-15 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('penalty_type', models.CharField(choices=[('late_payment', 'Late Payment'), ('unauthorized_signage', 'Unauthorized Signage'), ('health_safety', 'Health and Safety Violation'), ('noise_pollution', 'Noise Pollution'), ('illegal_subletting', 'Illegal Subletting'), ('trading_violation', 'Trading Violation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived'), ('disputed', 'Disputed')], default='unpaid', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_ref', models.CharField(blank=True, max_length=100)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_penalties', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='shops.shop')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shutdown_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('reason', models.CharField(choices=[('non_payment', 'Non Payment of Dues'), ('safety_violation', 'Safety Violation'), ('illegal_activity', 'Illegal Activity'), ('court_order', 'Court Order'), ('structural_risk', 'Structural Risk'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted'), ('pending', 'Pending Enforcement')], default='pending', max_length=10)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_shutdowns', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_shutdowns', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutdowns', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutdowns', to='shops.shop')),
            ],
            options={
                'db_table': 'shutdown_notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
