# Generated by Django 6.0.4 on 2026-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalty',
            name='fine_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='fine_payment_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='penalty',
            name='operator_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='operator_response',
            field=models.TextField(blank=True),
        ),
    ]
