# Generated by Django 6.0.4 on 2026-08-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0002_penalty_fine_paid_penalty_fine_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdownnotice',
            name='operator_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shutdownnotice',
            name='operator_response',
            field=models.TextField(blank=True),
        ),
    ]
