# Generated by Django 6.0.4 on 2026-06-02 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('facility_maintenance', 'Facility Maintenance'), ('legal_professional', 'Legal & Professional Fees'), ('event_agm', 'Event/AGM Costs'), ('staff_welfare', 'Staff Welfare'), ('security', 'Security'), ('sanitation', 'Sanitation'), ('it_technology', 'IT & Technology'), ('office_supplies', 'Office Supplies'), ('public_relations', 'Public Relations'), ('emergency_repairs', 'Emergency Repairs'), ('capital_expenditure', 'Capital Expenditure'), ('other', 'Other')], max_length=30)),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='expenses/evidence/')),
                ('status', models.CharField(choices=[('pending_treasurer', 'Pending Treasurer Approval'), ('pending_secretary', 'Pending Secretary General Approval'), ('pending_president', 'Pending President Approval'), ('pending_bot', 'Pending BOT Ratification'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending_treasurer', max_length=30)),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('requires_bot', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('role', models.CharField(choices=[('treasurer', 'Treasurer'), ('secretary_general', 'Secretary General'), ('president', 'President'), ('bot', 'Board of Trustees')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_approvals', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='expenses.expense')),
            ],
            options={
                'db_table': 'expense_approval_steps',
                'ordering': ['step_number'],
                'unique_together': {('expense', 'step_number')},
            },
        ),
    ]
