# Generated by Django 6.0.4 on 2026-09-10 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_association'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bot_actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='bot_actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_actioned_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='bot_resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_evidence',
            field=models.FileField(blank=True, null=True, upload_to='expenses/evidence/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending_treasurer', 'Pending Treasurer Approval'), ('pending_secretary', 'Pending Secretary Approval'), ('pending_president', 'Pending President Approval'), ('pending_bot', 'Pending BOT Ratification'), ('approved', 'Approved'), ('deferred', 'Deferred to Next Meeting'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_treasurer', max_length=30),
        ),
    ]
