# Generated by Django 6.0.4 on 2026-04-29 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('electricity_ekedc', 'Electricity (EKEDC)'), ('electricity_genlevy', 'Electricity (Generator Levy)'), ('water', 'Water (Lagos Water Corp)'), ('waste', 'Waste Management'), ('security', 'Security Levy'), ('other', 'Other Utility')], max_length=30)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('billing_period', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('pos', 'POS'), ('cash', 'Cash'), ('online', 'Online Payment'), ('ussd', 'USSD')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='bills/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_amount', models.BigIntegerField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_payments', to='shops.shop')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_external_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=30, unique=True)),
                ('billing_period', models.CharField(max_length=20)),
                ('management_fee', models.BigIntegerField(default=0)),
                ('maintenance_levy', models.BigIntegerField(default=0)),
                ('electricity', models.BigIntegerField(default=0)),
                ('water', models.BigIntegerField(default=0)),
                ('vat', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid (Pending Verification)'), ('verified', 'Verified')], default='unpaid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_ref', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_bills', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='shops.shop')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-created_at'],
                'unique_together': {('shop', 'billing_period')},
            },
        ),
    ]
