# Generated by Django 6.0.4 on 2026-08-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_payments', to='bills.bill'),
        ),
    ]
