# Generated by Django 6.0.4 on 2026-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('op', 'Operator'), ('is', 'Association Executive'), ('bot', 'Board of Trustees'), ('adv', 'Advisor'), ('sa', 'Super Admin')], default='op', max_length=10),
        ),
    ]
