# Generated by Django 6.0.4 on 2026-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ipos',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary_general', 'Secretary General'), ('treasurer', 'Treasurer'), ('legal_adviser', 'Legal Adviser'), ('pro', 'Public Relations Officer'), ('chairman', 'BOT Chairman'), ('none', 'None')], default='none', max_length=30),
        ),
    ]
