# Generated by Django 6.0.4 on 2026-07-22 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('advert', 'Advert Fee'), ('toilet', 'Toilet Access'), ('bill', 'HFP Bill')], max_length=15)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.BigIntegerField()),
                ('association_share_pct', models.IntegerField()),
                ('platform_share_pct', models.IntegerField()),
                ('association_amount', models.BigIntegerField()),
                ('platform_amount', models.BigIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distributions', to='associations.association')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revenue_distributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('association', 'Association Revenue'), ('platform', 'Platform Revenue (Iprolance)')], max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.BigIntegerField(default=0)),
                ('total_earned', models.BigIntegerField(default=0)),
                ('total_withdrawn', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_wallet', to='associations.association')),
            ],
            options={
                'db_table': 'revenue_wallets',
            },
        ),
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.BigIntegerField()),
                ('source_type', models.CharField(choices=[('subscription', 'Subscription Fee'), ('advert', 'Advert Fee'), ('toilet', 'Toilet Subscription'), ('bill', 'HFP Bill Payment'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revenue_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='revenue.revenuewallet')),
            ],
            options={
                'db_table': 'revenue_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
