# Generated by Django 6.0.4 on 2026-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuedistribution',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription Fee'), ('advert', 'Advert Fee'), ('toilet', 'Toilet Subscription'), ('bill', 'HFP Bill Payment'), ('external_payment', 'External Payment'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual Adjustment')], max_length=16),
        ),
    ]
