# Generated by Django 6.0.4 on 2026-05-14 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleblowerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('financial_irregularity', 'Financial Irregularity'), ('vendor_collusion', 'Vendor Collusion'), ('harassment', 'Harassment'), ('corruption', 'Corruption'), ('safety_violation', 'Safety Violation'), ('misconduct', 'Staff Misconduct'), ('other', 'Other')], max_length=30)),
                ('narrative', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wb_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whistleblower_reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WhistleblowerUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='whistleblower.whistleblowerreport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wb_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whistleblower_updates',
                'ordering': ['created_at'],
            },
        ),
    ]
