# Generated by Django 6.0.4 on 2026-06-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('whistleblower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblowerreport',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whistleblower_reports', to='associations.association'),
        ),
    ]
