# Generated by Django 6.0.4 on 2026-06-05 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period', models.CharField(max_length=20, unique=True)),
                ('total_bills', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('unverified_count', models.IntegerField(default=0)),
                ('gap_count', models.IntegerField(default=0)),
                ('total_billed', models.BigIntegerField(default=0)),
                ('total_paid', models.BigIntegerField(default=0)),
                ('total_variance', models.BigIntegerField(default=0)),
                ('external_payments_count', models.IntegerField(default=0)),
                ('external_payments_amount', models.BigIntegerField(default=0)),
                ('settlement_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'period_summaries',
                'ordering': ['-billing_period'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period', models.CharField(max_length=20)),
                ('iscooa_amount', models.BigIntegerField(default=0)),
                ('operator_amount', models.BigIntegerField(default=0)),
                ('operator_method', models.CharField(blank=True, max_length=50)),
                ('paid_ref', models.CharField(blank=True, max_length=100)),
                ('variance', models.BigIntegerField(default=0)),
                ('match_status', models.CharField(choices=[('match', 'Match'), ('unverified', 'Unverified'), ('gap', 'Gap')], default='unverified', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='bills.bill')),
                ('external_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='bills.externalpayment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_records', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='shops.shop')),
            ],
            options={
                'db_table': 'reconciliation_records',
                'ordering': ['-billing_period', 'shop__shop_number'],
            },
        ),
    ]
