# Generated by Django 6.0.4 on 2026-04-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_number', models.CharField(max_length=20, unique=True)),
                ('block', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('E', 'Block E'), ('F', 'Block F'), ('G', 'Block G'), ('H', 'Block H')], max_length=5)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.CharField(choices=[('leased', 'Leased'), ('owned', 'Owned'), ('subleased', 'Subleased')], default='leased', max_length=20)),
                ('landlord', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('nature', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('electricity_type', models.CharField(choices=[('metered', 'Metered'), ('flat_rate', 'Flat Rate')], default='flat_rate', max_length=20)),
                ('iscooa_position', models.CharField(blank=True, max_length=50)),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='shops/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shops',
                'ordering': ['block', 'shop_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('sales_associate', 'Sales Associate'), ('cashier', 'Cashier'), ('store_keeper', 'Store Keeper'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shop')),
            ],
            options={
                'db_table': 'staff_members',
                'ordering': ['full_name'],
            },
        ),
    ]
