"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv


# Load .env file
load_dotenv()

# Validate environment variables on startup
from config.env_validator import validate_environment
validate_environment()


# Base directory points to backend/
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-secret-key')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',') + ['.onrender.com']

# Application definition

# ─── INSTALLED APPS ───────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'axes',

    # Our apps
    'accounts',
    'kyc',
    'shops',
    'bills',
    'subscriptions',
    'wallet',
    'adverts',
    'toilet',
    'expenses',
    'resolutions',
    'disputes',
    'polls',
    'notifications',
    'publications',
    'whistleblower',
    'enforcement',
    'audit',
    'revenue',
    'reconciliation',
    'associations',
]

# ─── MIDDLEWARE ───────────────────────────────────────────────────────────────
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',       # ← add after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',                   # ← add before messages
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ─── AUTHENTICATION BACKENDS ──────────────────────────────────────────────────
# axes must be first to intercept failed login attempts
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]



# ─── SECURITY SETTINGS ────────────────────────────────────────────────────────

# Django Axes — brute force login protection
AXES_FAILURE_LIMIT          = 5
# Lock account after 5 failed login attempts
AXES_COOLOFF_TIME           = 1
# Lock lasts 1 hour
AXES_LOCKOUT_CALLABLE       = None
AXES_RESET_ON_SUCCESS       = True
# Reset failure count on successful login
AXES_LOCKOUT_PARAMETERS     = ['username', 'ip_address']
# Lock by both username and IP

# Rate limiting
RATELIMIT_ENABLE            = True
RATELIMIT_USE_CACHE         = 'default'

# CORS — tightened for production
# In development we allow localhost
# In production set CORS_ALLOWED_ORIGINS in .env
CORS_ALLOW_CREDENTIALS      = True
CORS_ALLOW_METHODS          = [
    'DELETE', 'GET', 'OPTIONS',
    'PATCH', 'POST', 'PUT',
]
CORS_ALLOW_HEADERS          = [
    'accept', 'accept-encoding', 'authorization',
    'content-type', 'dnt', 'origin',
    'user-agent', 'x-csrftoken', 'x-requested-with',
]

# Security headers — active in production (DEBUG=False)
SECURE_BROWSER_XSS_FILTER          = True
SECURE_CONTENT_TYPE_NOSNIFF         = True
X_FRAME_OPTIONS                     = 'DENY'
SECURE_REFERRER_POLICY              = 'same-origin'

# In production only (set these when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT             = True
    SECURE_HSTS_SECONDS             = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
    SECURE_HSTS_PRELOAD             = True
    SESSION_COOKIE_SECURE           = True
    CSRF_COOKIE_SECURE              = True

# Static files with whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Cache for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'iscooa-facitech-cache',
    }
}

# ─── URL & TEMPLATES ─────────────────────────────────────────────────────────
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ─── DATABASE (PostgreSQL) ────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres.nopnqomivvhljmxycoid'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'Q2E-Cm99kGVjZ$'),
        'HOST': os.getenv('DB_HOST', 'aws-0-eu-west-1.pooler.supabase.com'),
        'PORT': os.getenv('DB_PORT', '5432'),
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': os.getenv('DB_NAME', 'iscooa_facitech'),
    #     'USER': os.getenv('DB_USER', 'postgres'),
    #     'PASSWORD': os.getenv('DB_PASSWORD', ''),
    #     'HOST': os.getenv('DB_HOST', 'localhost'),
    #     'PORT': os.getenv('DB_PORT', '5432'),
    # }
}

import dj_database_url
database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.config(default=database_url)



# ─── CUSTOM USER MODEL ────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'accounts.User'


# ─── REST FRAMEWORK ──────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}




# ─── SWAGGER / API DOCUMENTATION ──────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE':       'ISCOOA Facitech API',
    'DESCRIPTION': '''
ISCOOA Facitech is the official digital management and billing platform
for ISCOOA — Ikota Shopping Complex Owners and Operators Association, VGC, Lagos.

Developed by Iprolance LLC. Powered by Cool Microfinance Bank.

## Authentication
All endpoints except `/api/v1/auth/login/` and `/api/v1/auth/register/`
require a Bearer JWT token in the Authorization header.

**Format:** `Authorization: Bearer <your_access_token>`

## Roles
The platform has 6 roles — each with a different set of accessible endpoints:
- `op` — Operator (shop owner)
- `is` — ISCOOA Executive (President, Treasurer, Secretary General etc)
- `bot` — Board of Trustees
- `adv` — Advisor
- `sa` — Iprolance Super Admin

## Amounts
All monetary amounts are stored and transmitted in **kobo** (integer).
Divide by 100 to get Naira. Every response includes a companion `_naira` field for display.

## Support
Contact: Iprolance LLC
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # JWT Auth button in Swagger UI
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },

    # Group endpoints by app/module
    'TAGS': [
        {'name': 'Auth',            'description': 'Login, registration and account management'},
        {'name': 'KYC',             'description': '11-step operator onboarding wizard'},
        {'name': 'Shops',           'description': 'Shop management and staff sub-accounts'},
        {'name': 'Bills',           'description': 'HFP invoices and external payments'},
        {'name': 'Subscriptions',   'description': 'Platform subscription fees and payment cycles'},
        {'name': 'Wallet',          'description': 'Cool MFB wallet top-up and transaction history'},
        {'name': 'Adverts',         'description': 'Operator advert submissions and marketplace'},
        {'name': 'Toilet',          'description': 'Per-person toilet access subscriptions'},
        {'name': 'Disputes',        'description': 'Operator-raised disputes and ISCOOA investigation'},
        {'name': 'Polls',           'description': 'ISCOOA polls with live operator voting'},
        {'name': 'Whistleblower',   'description': 'Anonymous reports — President and Legal Adviser only'},
        {'name': 'Notifications',   'description': 'Per-user notification feed and preferences'},
        {'name': 'Enforcement',     'description': 'Penalties and shop shutdowns'},
        {'name': 'Audit',           'description': 'Append-only platform audit log'},
        {'name': 'Publications',    'description': 'Email/SMS blasts and announcements'},
        {'name': 'Resolutions',     'description': 'BOT resolutions and advisory notes'},
        {'name': 'Expenses',        'description': 'Multi-step expense approval workflow'},
        {'name': 'Reconciliation',  'description': 'Dual-party billing and payment ledger'},
        {'name': 'Overview',        'description': 'Portal dashboards for each role'},
        {'name': 'Associations', 'description': 'Association management and white-label configuration'},
    ],

    'SORT_OPERATIONS': False,
    'ENUM_GENERATE_CHOICE_DESCRIPTION': True,
}


# ─── JWT SETTINGS ─────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('ACCESS_TOKEN_LIFETIME_MINUTES', 60))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('REFRESH_TOKEN_LIFETIME_DAYS', 7))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ─── CORS ─────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000,http://127.0.0.1:3000,https://facitech.netlify.app'
).split(',')


# ─── PAYSTACK ─────────────────────────────────────────────────────────────────
PAYSTACK_SECRET_KEY    = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY    = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_CALLBACK_URL  = os.getenv('PAYSTACK_CALLBACK_URL', 'https://facitech.netlify.app/wallet/callback') # -> change this to live url to redirct to frontend
PAYSTACK_WEBHOOK_URL   = os.getenv('PAYSTACK_WEBHOOK_URL', 'https://facitech-backendtest.onrender.com/api/v1/wallet/paystack/webhook/')



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ─── STATIC FILES CONFIGURATION ──────────────────────────────────────────────
# Django requires these regardless of whether you use cloud storage or local disk
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ─── FILE STORAGE ─────────────────────────────────────────────────────────────
USE_CLOUD_STORAGE = os.getenv('USE_CLOUD_STORAGE', 'False') == 'True'

if USE_CLOUD_STORAGE:
    # ── Supabase Storage (S3-compatible) ──────────────────────────────
    AWS_ACCESS_KEY_ID       = os.getenv('SUPABASE_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY   = os.getenv('SUPABASE_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('SUPABASE_STORAGE_BUCKET', 'facitech-media')
    AWS_S3_REGION_NAME      = os.getenv('SUPABASE_S3_REGION', 'us-east-1')
    AWS_S3_ENDPOINT_URL     = os.getenv('SUPABASE_S3_ENDPOINT')

    # CRITICAL: Forces django-storages to communicate correctly with Supabase
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE  = 'path'
    AWS_DEFAULT_ACL          = None  # Supabase doesn't support S3 Object ACLs
    AWS_S3_FILE_OVERWRITE    = False
    AWS_QUERYSTRING_AUTH     = False # Disables S3 query signatures for public assets

    # Modern Django 4.2+ Storage Routing Layout
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Public URLs must target Supabase's native REST wrapper, NOT the S3 API Gateway
    PROJECT_ID = "nopnqomivvhljmxycoid"

    # ⬇⬇⬇ THIS IS THE NEW LINE — it's the only thing missing from your file.
    # Without it, django-storages ignores MEDIA_URL below and builds file.url
    # from AWS_S3_ENDPOINT_URL instead (the /storage/v1/s3/... signing endpoint),
    # which is why you're getting "Missing signature" / 403 errors.
    AWS_S3_CUSTOM_DOMAIN = f"{PROJECT_ID}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"

    MEDIA_URL = f"https://{PROJECT_ID}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}/"
    MEDIA_ROOT = ''

else:
    # ── Local filesystem (development only) ────────────────────────────
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# ─── FILE UPLOAD SETTINGS ─────────────────────────────────────────────────────
# Maximum upload size: 5MB as per the brief
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

# Allowed file types for KYC documents
ALLOWED_KYC_IMAGE_TYPES  = ['image/jpeg', 'image/png', 'image/jpg']
ALLOWED_KYC_DOC_TYPES    = ['image/jpeg', 'image/png', 'image/jpg', 'application/pdf']
ALLOWED_EVIDENCE_TYPES   = ['image/jpeg', 'image/png', 'image/jpg', 'application/pdf']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'