# Generated by Django 6.0.4 on 2026-05-20 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ann_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('category', models.CharField(choices=[('general_notice', 'General Notice'), ('emergency', 'Emergency'), ('meeting', 'Meeting'), ('compliance', 'Compliance'), ('agm', 'AGM')], default='general_notice', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('pub_type', models.CharField(choices=[('email', 'Email Blast'), ('sms', 'SMS Blast'), ('announcement', 'Announcement')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_group', models.CharField(choices=[('all_operators', 'All Active Operators'), ('exco_members', 'Exco Members Only'), ('defaulters', 'Defaulters Only'), ('bot_members', 'Board of Trustees'), ('all', 'Everyone')], default='all_operators', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('sent', 'Sent'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='publications/attachments/')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('open_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-created_at'],
            },
        ),
    ]
