# Generated by Django 6.0.4 on 2026-07-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overdue_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
