# Generated by Django 6.0.4 on 2026-07-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='associations.association'),
        ),
        migrations.AddField(
            model_name='advert',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='advert',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('promo', 'Promo'), ('new_stock', 'New Stock'), ('vacancy', 'Vacancy'), ('services', 'Services'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('offline', 'Taken Offline')], default='pending', max_length=20),
        ),
    ]
