# Generated by Django 6.0.4 on 2026-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_approved_at_advert_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='advert',
            name='contact_facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='advert',
            name='contact_instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='advert',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='advert',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
