# Generated by Django 6.0.4 on 2026-06-01 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('res_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('full_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Vote'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='draft', max_length=10)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('yea_count', models.IntegerField(default=0)),
                ('nay_count', models.IntegerField(default=0)),
                ('abstain_count', models.IntegerField(default=0)),
                ('ratified_date', models.DateTimeField(blank=True, null=True)),
                ('signatories', models.JSONField(blank=True, default=list)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resolutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_notes', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_notes', to='resolutions.resolution')),
            ],
            options={
                'db_table': 'advisory_notes',
                'ordering': ['submitted_at'],
                'unique_together': {('resolution', 'advisor')},
            },
        ),
        migrations.CreateModel(
            name='ResolutionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('yea', 'Yea'), ('nay', 'Nay'), ('abstain', 'Abstain')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('bot_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_votes', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resolutions.resolution')),
            ],
            options={
                'db_table': 'resolution_votes',
                'unique_together': {('resolution', 'bot_member')},
            },
        ),
    ]
