# Generated by Django 6.0.4 on 2026-04-28 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kyc_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('docs_requested', 'Documents Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('member_number', models.CharField(blank=True, max_length=30, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('docs_note', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_approvals', to=settings.AUTH_USER_MODEL)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_applications',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='KYCBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('nature', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cac_number', models.CharField(blank=True, max_length=50)),
                ('cac_file', models.FileField(blank=True, null=True, upload_to='kyc/cac/')),
                ('year_started', models.IntegerField(blank=True, null=True)),
                ('first_year', models.IntegerField(blank=True, null=True)),
                ('relocated', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_business',
            },
        ),
        migrations.CreateModel(
            name='KYCDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndpr_consent', models.BooleanField(default=False)),
                ('declaration', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_declaration',
            },
        ),
        migrations.CreateModel(
            name='KYCDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='kyc/docs/passport/')),
                ('gov_id', models.FileField(blank=True, null=True, upload_to='kyc/docs/gov_id/')),
                ('cac_certificate', models.FileField(blank=True, null=True, upload_to='kyc/docs/cac/')),
                ('tenancy_lease', models.FileField(blank=True, null=True, upload_to='kyc/docs/tenancy/')),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='kyc/docs/shop/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='KYCEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_emergency_contact',
            },
        ),
        migrations.CreateModel(
            name='KYCFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_finance',
            },
        ),
        migrations.CreateModel(
            name='KYCGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_guarantor',
            },
        ),
        migrations.CreateModel(
            name='KYCIscooaStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(blank=True, default='None', max_length=100)),
                ('previous_positions', models.TextField(blank=True)),
                ('years_as_member', models.IntegerField(default=0)),
                ('has_disputes', models.BooleanField(default=False)),
                ('dispute_note', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iscooa_standing', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_iscooa_standing',
            },
        ),
        migrations.CreateModel(
            name='KYCNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_next_of_kin',
            },
        ),
        migrations.CreateModel(
            name='KYCPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('nin', models.CharField(blank=True, max_length=11)),
                ('bvn', models.CharField(blank=True, max_length=11)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('id_type', models.CharField(blank=True, max_length=30)),
                ('id_file', models.FileField(blank=True, null=True, upload_to='kyc/ids/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='kyc/passports/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_personal',
            },
        ),
        migrations.CreateModel(
            name='KYCReviewNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='kyc.kycapplication')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_review_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=5)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.CharField(blank=True, choices=[('leased', 'Leased'), ('owned', 'Owned'), ('subleased', 'Subleased')], max_length=20)),
                ('landlord', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('nature', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='kyc/shops/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_shops', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_shops',
            },
        ),
        migrations.CreateModel(
            name='KYCStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_staff_count', models.IntegerField(default=0)),
                ('intends_to_register', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to='kyc.kycapplication')),
            ],
            options={
                'db_table': 'kyc_staff',
            },
        ),
    ]
