# Generated by Django 6.0.4 on 2026-06-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_applications', to='associations.association'),
        ),
    ]
