# Generated by Django 6.0.4 on 2026-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycapplication_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('docs_requested', 'Documents Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
