# Generated by Django 6.0.4 on 2026-05-06 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_kobo', models.BigIntegerField(default=10000)),
                ('monthly_kobo', models.BigIntegerField(default=100000)),
                ('quarterly_kobo', models.BigIntegerField(default=250000)),
                ('annual_kobo', models.BigIntegerField(default=900000)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toilet_pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toilet_pricing',
            },
        ),
        migrations.CreateModel(
            name='ToiletSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('person_type', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=10)),
                ('plan', models.CharField(choices=[('daily', 'Daily Pass'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('access_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_registrations', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_subscriptions', to='shops.shop')),
            ],
            options={
                'db_table': 'toilet_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
