# Generated by Django 6.0.4 on 2026-06-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletpricing',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toilet_pricing', to='associations.association'),
        ),
        migrations.AddField(
            model_name='toiletsubscription',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toilet_subscriptions', to='associations.association'),
        ),
        migrations.AlterUniqueTogether(
            name='toiletpricing',
            unique_together={('association', 'is_active')},
        ),
    ]
