# Generated by Django 6.0.4 on 2026-05-15 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('adverts', 'Adverts'), ('disputes', 'Disputes'), ('polls', 'Polls'), ('penalties', 'Penalties'), ('payments', 'Payments'), ('kyc', 'KYC'), ('subscriptions', 'Subscriptions'), ('toilet', 'Toilet'), ('general', 'General')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_bills', models.BooleanField(default=True)),
                ('email_adverts', models.BooleanField(default=True)),
                ('email_disputes', models.BooleanField(default=True)),
                ('email_polls', models.BooleanField(default=True)),
                ('email_penalties', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_kyc', models.BooleanField(default=True)),
                ('email_subscriptions', models.BooleanField(default=True)),
                ('email_toilet', models.BooleanField(default=False)),
                ('email_general', models.BooleanField(default=True)),
                ('sms_bills', models.BooleanField(default=False)),
                ('sms_adverts', models.BooleanField(default=False)),
                ('sms_disputes', models.BooleanField(default=True)),
                ('sms_polls', models.BooleanField(default=False)),
                ('sms_penalties', models.BooleanField(default=True)),
                ('sms_payments', models.BooleanField(default=True)),
                ('sms_kyc', models.BooleanField(default=True)),
                ('sms_subscriptions', models.BooleanField(default=False)),
                ('sms_toilet', models.BooleanField(default=False)),
                ('sms_general', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
